### ISSUE TITLE
Possible race condition in zookeeper consumer?

### ISSUE THREAD

**Issue by varunv** [DataDog/brod#19]
I have noticed that when couple of hundred consumers are killed and launched (over a few seconds) for single topic, a small amount of partitions do not get assigned at all. 

My thought was there is a race condition of sorts when a consumer is querying zookeeper to find out about other consumers and the kafka brokers, but by the time it retrieves the information, another consumer might have been killed.

I got around this by waiting for the broker partition per consumer to stabilize before polling, and I do this every time a rebalance happens.

What do you think, though? Is this a real issue, or a possible side affect of my application?

**Comment by clofresh** [comment]
It's real issue. We run into it on our end from time to time. What happens is that two or more consumers claim the same partition and end up omitting another partition. I haven't been able to track down the issue and have worked around it by using simple (non-zk) consumers with statically assigned partitions.

If you're be interested in trying to figure out and fix the bug, I'd be happy to help test out any pull requests you might have.

**Comment by varunv** [comment]
In our case, I just discovered that it actually seems to be a problem in zookeeper itself when killing and starting consumers. After restarting say about 30 consumers, there almost always seems to be a few "residual" consumer in the "ids" directory in zookeeper. This then leads to partitions being assigned to imaginary consumers.

**Comment by technovangelist** [comment]
Hi @varunv - Thanks for your interest. This repo is no longer maintained and will be removed in 3 months (on or soon after June 30, 2015). If you are still interested in the functionality offered, we suggest looking at https://github.com/mumrah/kafka-python which is being actively maintained.
