### ISSUE TITLE
noob question

### ISSUE THREAD

**Issue by anentropic** [DataDog/brod#20]
Are the messages I get back from `fetch` supposed to be decoded into strings?  I'm seeing gobbledegook:

```
In [13]: for offset, message in kafka.fetch("adlogs", offset=0):
    print '%s: %s' % (offset, message)
   ....: 
0: %JA�;7yd�`�����#.FE�$n"(�Ȩ-6��  D�.��7�J�lc�
���/�ߤ-���(�(�>]m��2hĚ
                        ��Z�h�-:ʔ�s���>L��Զ��apB� �t���U�ΝB�X��8^�Ӄ��K����t2�6�#���y7���ew�DI�A�Ys�,�����o?LZ�N�^����S���{R��
}E60�l}� �[�/
               ����
```

If I run the `kafka-console-consumer.sh` that comes with Kafka I see readable stuff in the messages.

I'm running 0.7.2 but as far as I can tell I haven't got compression turned on anywhere.  Having a look through the source the `VERSION_0_7 = False` flag looks a bit ominous... could that be the problem, or I'm doing it all wrong?

**Comment by clofresh** [comment]
Those should be decoding as strings. I haven't tested brod with 0.7 but @rasprague has done some work to get brod to work with 0.7, maybe try out his fork: https://github.com/rasprague/brod.git

**Comment by technovangelist** [comment]
hi @anentropic - Thanks for your interest. This repo is no longer maintained and will be removed in 3 months (on or soon after June 30, 2015). If you are still interested in the functionality offered, we suggest looking at https://github.com/mumrah/kafka-python which is being actively maintained.
