### ISSUE TITLE
I got a lot of messy code in consuming

### ISSUE THREAD

**Issue by fozzmarc** [DataDog/brod#25]
like this

``` shell
TTCLUSTER_A0"}����d{
```

and sometimes arise an ERROR:

``` shell
ERROR:brod:Unexpected magic byte: 1 (expecting 0)
ERROR:brod:Checksum failure at offset 21131494
```

**Comment by technovangelist** [comment]
Hi @fozzmarc - Thanks for your interest. This repo is no longer maintained and will be removed in 3 months (on or soon after June 30, 2015). If you are still interested in the functionality offered, we suggest looking at https://github.com/mumrah/kafka-python which is being actively maintained.
