### ISSUE TITLE
Poll start/end for ZKConsumer

### ISSUE THREAD

**Issue by vanderveld** [DataDog/brod#27]
Any plans to add a start and end time for polling? I'm interested in a way to poll until I'm up-to-date and then stop. Thanks.

**Comment by technovangelist** [comment]
hi @vanderveld - Thanks for your interest. This repo is no longer maintained and will be removed in 3 months (on or soon after June 30, 2015). If you are still interested in the functionality offered, we suggest looking at https://github.com/mumrah/kafka-python which is being actively maintained.
