### ISSUE TITLE
Old zc.zk

### ISSUE THREAD

**Issue by amorton** [DataDog/brod#3]
Setup py has 

``` py
install_requires = [
    "zc.zk==0.2.0",
]
```

The current version of zc.zk is 0.5.2 http://pypi.python.org/pypi/zc.zk/0.5.2

Is there a reason for locking to a specific version ? All the tests pass with 0.6.2 agains the 0.7.0 Kafka rel.

**Comment by amorton** [comment]
Should say I needed to install http://pypi.python.org/pypi/zc-zookeeper-static

**Comment by ormsbee** [comment]
It was locked to a specific version just because the Zope folks are releasing a new point version update every week or so, and I didn't want to inadvertently upgrade our stuff to something untested without advanced notice. I bumped it to 0.5.2.
