### ISSUE TITLE
Exception while reading: 'Q' format code?

### ISSUE THREAD

**Issue by sthomas-github** [DataDog/brod#31]
I'm running the brod client against a 0.7.2 release of Kafka.  I can write to Kafka w/o error, but when I try to read with the following code, I get an error:

``` python
import brod

def check_kafka_write(host):
    try:
        kafka = brod.Kafka(host=host)
        kafka.produce('test', ['ping'])
    except Exception as e:
        print str(e)
        return None
    else:
        print 'Success'
    return True

def check_kafka_read(host):
    kafka = brod.Kafka(host=host)
    for offset, message in kafka.fetch("test", offset=brod.EARLIEST_OFFSET):
        print message

if __name__ == '__main__':
    host = '<ip-address>'
    check_kafka_write(host)
    check_kafka_read(host)
```

Execution looks like this:

> python check_kafka.py
> Success
> Traceback (most recent call last):
>   File "check_kafka.py", line 22, in <module>
>     check_kafka_read(host)
>   File "check_kafka.py", line 16, in check_kafka_read
>     for offset, message in kafka.fetch("monica", offset=brod.EARLIEST_OFFSET):
>   File "C:\Anaconda\lib\site-packages\brod-0.4.3-py2.7.egg\brod\base.py", line 324, in fetch
>     offset, partition, fetch_size)
>   File "C:\Anaconda\lib\site-packages\brod-0.4.3-py2.7.egg\brod\base.py", line 550, in _fetch_request
>     bin_request = struct.pack('>HH%dsIQI' % topic_length, *request)
> struct.error: integer out of range for 'Q' format code

**Comment by clofresh** [comment]
brod only supports kafka 0.6, sorry.
