### ISSUE TITLE
Multi-fetch needs to be implemented

### ISSUE THREAD

**Issue by ormsbee** [DataDog/brod#5]
Currently, ZKConsumer uses a series of separate fetch() requests. The Kafka class should support a multi-fetch method that returns a FetchResult, and ZKConsumer should use this.

**Comment by technovangelist** [comment]
Hi @ormsbee - Thanks for your interest. This repo is no longer maintained and will be removed in 3 months (on or soon after June 30, 2015). If you are still interested in the functionality offered, we suggest looking at https://github.com/mumrah/kafka-python which is being actively maintained.
