### ISSUE TITLE
Multi-produce needs to be implemented

### ISSUE THREAD

**Issue by ormsbee** [DataDog/brod#6]
Like multi-fetch, we need to implement multi-produce in the base Kafka object, and use it to group produce calls from ZKProducer.

**Comment by technovangelist** [comment]
Hi @ormsbee - Thanks for your interest. This repo is no longer maintained and will be removed in 3 months (on or soon after June 30, 2015). If you are still interested in the functionality offered, we suggest looking at https://github.com/mumrah/kafka-python which is being actively maintained.
