### ISSUE TITLE
Compression support

### ISSUE THREAD

**Issue by ormsbee** [DataDog/brod#7]
We don't support compressed messages yet, as per:

https://cwiki.apache.org/confluence/display/KAFKA/Compression

(I have a description of it https://cwiki.apache.org/confluence/display/KAFKA/Writing+a+Driver+for+Kafka as well, though I can't verify the accuracy of it yet.)

Implementing this will probably also mean shifting the parsing of messages to the MessageSet class, so that it can calculate the offsets properly.

**Comment by anentropic** [comment]
it's not as pretty as brod/pykafka, but this python client has compressed message support, maybe parts can be borrowed: https://github.com/mumrah/kafka-python
